### ISSUE TITLE
Reminder overlay is constantly showing that I need to re-pot

### ISSUE THREAD

**Issue by User1893** [AnkouOSRS/unpotted-reminder#15]
When I'm killing a boss using divine potions, the reminder popup appears every time the boss respawns. I have the "boost thresholds" set to 109 and even when I'm boosted to 118 from a divine pot, the potion reminder will still appear every time an enemy respawns. Seems to happen across all combat styles and all attack styles (aggressive, attack, defensive, etc.). Not sure if I'm dumb as hell and missing something or if this is an actual bug, but I've tried turning settings in the plugin on/off and haven't been able to get it to work as intended.

Thanks and I appreciate any insight!

**Comment by AnkouOSRS** [comment]
The threshold is how much you want to be boosted **by** not what level you want to be boosted **to**. So if you're level 99 and you set the threshold to 10 for melee, you'll be alerted any time your level falls below 109
