### ISSUE TITLE
Divine Super Strength (with no Divine Super Attack) wont stop spamming

### ISSUE THREAD

**Issue by nickrs123** [AnkouOSRS/unpotted-reminder#16]
I am using only a divine super strength but the plugin seems to base the "melee boost threshold" on my attack level. I don't want to use super attack potions. Is there a way to configure this so it doesn't constantly spam even though I am potted

![image](https://github.com/AnkouOSRS/unpotted-reminder/assets/169849458/a95ac82c-3385-483b-9968-f858569233b0)

**Comment by nickrs123** [comment]
update, this is same issue in #13 opened on Jan 16 by [Whisperhelp](https://github.com/AnkouOSRS/unpotted-reminder/issues?q=is%3Aissue+is%3Aopen+author%3AWhisperhelp)

i commented on that as well, but this could be fixed by adding a checkbox whether you are training attack/str/defense for it to only check that stat

**Comment by AnkouOSRS** [comment]
Sorry for the delay on this, it's definitely something I'd like to get to

**Comment by AnkouOSRS** [comment]
Fixed by the latest update which allows you to select which boost to check for melee
