### ISSUE TITLE
Alert for magic not working as intended

### ISSUE THREAD

**Issue by CameronBurrell** [AnkouOSRS/unpotted-reminder#18]
The alert from magic pot reminder is not working I use divine magic pots and I don't get a reminder to use them

**Comment by AnkouOSRS** [comment]
Divine magic pots should work, can you send a screenshot of your plugin
settings and let me know what weapon/spell you're using? Make sure alert
for magic is enabled and the magic threshold is set to something reasonable.

**Comment by CameronBurrell** [comment]
Hey thanks for the fast response! 

the 2 main spells I use are my trident of the seas or my Accursed sceptre

![not attacking guard](https://github.com/AnkouOSRS/unpotted-reminder/assets/88734635/c2ee7c99-d9b5-487f-87dc-78e1e69cc023)
this image I am not attacking the guard with a divine range pot and 2 divine mage pots in my inventory

![attacking with bow i see the message](https://github.com/AnkouOSRS/unpotted-reminder/assets/88734635/769937ce-386c-4b8c-8c38-3d1c528edaef)
I attack with bow and I get the message to pot up 

![attacking with mage](https://github.com/AnkouOSRS/unpotted-reminder/assets/88734635/92af1fe5-0107-47ae-bf49-0181e318b98c)
In this image I attack the guard with magic I don't get the same message as with ranged when using the trident of seas or my other staffs to pot my divine mage pots


All settings for runelite are on the side of each image, as you can see all I did was tick the alert for mage on, everything else is default, thanks for reading and your time :)

**Comment by CameronBurrell** [comment]
the 2 main spells I use are my trident of the seas or my Accursed sceptre
