### ISSUE TITLE
Doesn't seem to work on my client

### ISSUE THREAD

**Issue by cloud-aspect** [AnkouOSRS/unpotted-reminder#2]
The plugin doesn't seem to work, which is a shame because I think it would be really useful.

Is there some way I can help you test it and troubleshoot the issue on my end?

What I'm doing: set melee threshold to 12, drink super def, atk, str pots, I start at +17 and while in combat allow the stat to drain to the point where the boost is only +11, nothing happens

Have I misunderstood how its suppose to work?

Attaching an image with my plugin settings

![image](https://user-images.githubusercontent.com/26804474/205142520-05721d15-0217-43c2-b77d-7f296aaca981.png)

**Comment by AnkouOSRS** [comment]
I think this issue might be because of the "Xp Threshold" setting. To be completely honest with you, I think I set the description to say 0 to disable but never actually included the logic for that. My bad! 

Try with a higher threshold for that as it is currently ignoring any xp drops above that number.

**Comment by AnkouOSRS** [comment]
Actually, I did add the logic for disabling that at 0. The real issue here is I didn't add support for super attack/str which I really should have. For melee I only added divine and regular super combats for the initial plugin release. I'll add the rest soon.

**Comment by cloud-aspect** [comment]
Thank you very much! Probably should add support for all combat boosting potions too, even the lesser ones

**Comment by AnkouOSRS** [comment]
Agreed. I went ahead and added regular combat, attack, and strength, as well as divine and regular super attack and strength. As soon as someone on the Runelite side approves it the plugin should work for you after updating. If not feel free to open another issue. Thanks for pointing this out.
