### ISSUE TITLE
Notify setting spams the alert and notifications

### ISSUE THREAD

**Issue by Salmiac23232** [AnkouOSRS/unpotted-reminder#7]
is this intended? if it is could we get an option for a single alert?

Thank you very much. otherwise this is great! nice for nmz

**Comment by AnkouOSRS** [comment]
This is a good suggestion, I can certainly see why this would be annoying.

I think notifying you more than once is fine if you remain unpotted as you
may have missed it the first time, but I think adding a setting for a cool
down would be nice.

**Comment by AnkouOSRS** [comment]
The notify cooldown is included in v1.0.4 which should be live on the plugin hub relatively shortly.
